// <auto-generated />
using System;
using HistoricalMuseumAudioGuide.Repository.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HistoricalMuseumAudioGuide.Repository.Migrations
{
    [DbContext(typeof(MuseumAudioGuideContext))]
    [Migration("20260713174237_AddStatusToTicketTypes")]
    partial class AddStatusToTicketTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExhibitTag", b =>
                {
                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ExhibitId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ExhibitTags", (string)null);
                });

            modelBuilder.Entity("ExhibitionExhibit", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.HasKey("ExhibitionId", "ExhibitId");

                    b.HasIndex("ExhibitId");

                    b.ToTable("ExhibitionExhibits", (string)null);
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AgeGroup__3214EC073267C0C0");

                    b.ToTable("AgeGroups");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AnalyticsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOfflineEvent")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageUsed")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ListeningDuration")
                        .HasColumnType("int");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("SearchQuery")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Analytic__3214EC076218A530");

                    b.HasIndex("VisitorId");

                    b.HasIndex(new[] { "ActionType" }, "IX_Analytics_ActionType");

                    b.HasIndex(new[] { "EventTimestamp" }, "IX_Analytics_EventTimestamp");

                    b.HasIndex(new[] { "ExhibitId" }, "IX_Analytics_Exhibit");

                    b.HasIndex(new[] { "MuseumId" }, "IX_Analytics_Museum");

                    b.ToTable("AnalyticsLogs");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07D4241A7D");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_AuditLogs_CreatedAt");

                    b.HasIndex(new[] { "EntityType" }, "IX_AuditLogs_EntityType");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditLogs_UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Bookmark__3214EC0743E83E00");

                    b.HasIndex("ExhibitId");

                    b.HasIndex(new[] { "VisitorId", "ExhibitId" }, "UQ_Bookmarks")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07A1949F6A");

                    b.HasIndex("MuseumId");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC079C960808");

                    b.HasIndex(new[] { "CategoryId", "LanguageCode" }, "UQ_CatTrans")
                        .IsUnique();

                    b.ToTable("CategoryTranslations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<long?>("PackageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PublishedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<int?>("TotalExhibits")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMediaFiles")
                        .HasColumnType("int");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__ContentV__3214EC07E2F5D8C8");

                    b.HasIndex("PublishedBy");

                    b.HasIndex(new[] { "MuseumId", "VersionNumber" }, "UQ_ContentVersion")
                        .IsUnique();

                    b.ToTable("ContentVersions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArmarkerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ARMarkerUrl");

                    b.Property<string>("AroverlayUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AROverlayUrl");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ExhibitCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("LocationX")
                        .HasColumnType("float");

                    b.Property<double?>("LocationY")
                        .HasColumnType("float");

                    b.Property<int?>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrcodeData")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QRCodeData");

                    b.Property<string>("QrcodeImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QRCodeImageUrl");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Exhibits__3214EC0728865193");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("MapId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "ExhibitCode" }, "UQ__Exhibits__5204E7405196F227")
                        .IsUnique()
                        .HasFilter("[ExhibitCode] IS NOT NULL");

                    b.ToTable("Exhibits");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitArasset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("OverlayImage");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ExhibitA__3214EC07649477FB");

                    b.HasIndex("ExhibitId");

                    b.ToTable("ExhibitARAssets", (string)null);
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__ExhibitI__3214EC07CB1C8F3E");

                    b.HasIndex("ExhibitId");

                    b.ToTable("ExhibitImages");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitMetadatum", b =>
                {
                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<int?>("AgeGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Era")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HistoricalEvent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExhibitId");

                    b.HasIndex("AgeGroupId");

                    b.ToTable("ExhibitMetadata");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioDuration")
                        .HasColumnType("int");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK__ExhibitT__3214EC074E3F7B08");

                    b.HasIndex(new[] { "ExhibitId", "LanguageCode" }, "UQ_ExhibitTrans")
                        .IsUnique();

                    b.ToTable("ExhibitTranslations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Exhibiti__3214EC0743051CE0");

                    b.HasIndex("MuseumId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Exhibiti__3214EC07A48C3DBB");

                    b.HasIndex(new[] { "ExhibitionId", "LanguageCode" }, "UQ_ExhibTrans")
                        .IsUnique();

                    b.ToTable("ExhibitionTranslations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NativeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Language__3214EC075A095684");

                    b.HasIndex(new[] { "LanguageCode" }, "UQ__Language__8B8C8A3446FA90F1")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.MapPoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Poitype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POIType");

                    b.HasKey("Id")
                        .HasName("PK__MapPOIs__3214EC07011CA550");

                    b.HasIndex("MapId");

                    b.ToTable("MapPOIs", (string)null);
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Vietnam");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Museums__3214EC07F64D086B");

                    b.ToTable("Museums");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.MuseumMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("FloorNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("MapImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MapName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MuseumMa__3214EC077DAA1EC5");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumMaps");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.OfflinePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArassetCount")
                        .HasColumnType("int")
                        .HasColumnName("ARAssetCount");

                    b.Property<int?>("AudioCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BuiltAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("ExhibitCount")
                        .HasColumnType("int");

                    b.Property<int?>("ImageCount")
                        .HasColumnType("int");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<long>("PackageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PackageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Building");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OfflineP__3214EC074C67D86D");

                    b.HasIndex("MuseumId");

                    b.HasIndex("VersionId");

                    b.ToTable("OfflinePackages");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__PaymentM__3214EC07DA605523");

                    b.HasIndex(new[] { "Name" }, "UQ__PaymentM__737584F65638694F")
                        .IsUnique();

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3214EC07E1106079");

                    b.HasIndex(new[] { "PermissionName" }, "UQ__Permissi__0FFDA357D7FD4E68")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07DF597E3F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshTokens_Token");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC077E061479");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616097A109F1")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SystemCo__3214EC07FFC5BA3B");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "ConfigKey" }, "UQ__SystemCo__4A3067846AFFD489")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TagGroupId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TagGroupId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TagGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Themes__3214EC074D21EDC9");

                    b.HasIndex("MuseumId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Tickets__3214EC07876BB3A3");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("VisitorId");

                    b.HasIndex(new[] { "TicketCode" }, "UQ__Tickets__598CF7A3F437EC5B")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__TicketTy__3214EC075DC34A40");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("MuseumId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__TourRout__3214EC07F00F9A99");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("MuseumId");

                    b.ToTable("TourRoutes");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRouteExhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("TourRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TourRout__3214EC07028FAC02");

                    b.HasIndex("ExhibitId");

                    b.HasIndex(new[] { "TourRouteId", "ExhibitId" }, "UQ_TourRouteExhibits")
                        .IsUnique();

                    b.ToTable("TourRouteExhibits");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRouteTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TourRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TourRout__3214EC07DB106995");

                    b.HasIndex(new[] { "TourRouteId", "LanguageCode" }, "UQ_TourRouteTrans")
                        .IsUnique();

                    b.ToTable("TourRouteTranslations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC07634B4F68");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("VisitorId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ__Transact__999B5229FB610A1E")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07BE722AC8");

                    b.HasIndex("MuseumId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AC9E29DD")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.VisitedExhibit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExhibitId")
                        .HasColumnType("int");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__VisitedE__3214EC072F597FFC");

                    b.HasIndex("MuseumId");

                    b.HasIndex(new[] { "ExhibitId" }, "IX_VisitedExhibits_Exhibit");

                    b.HasIndex(new[] { "VisitorId" }, "IX_VisitedExhibits_Visitor");

                    b.ToTable("VisitedExhibits");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("PreferredLang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("vi");

                    b.HasKey("Id")
                        .HasName("PK__Visitors__3214EC0718CE3833");

                    b.HasIndex(new[] { "DeviceId" }, "UQ__Visitors__49E123102804749D")
                        .IsUnique();

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ExhibitTag", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", null)
                        .WithMany()
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibitTags_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibitTags_Tag");
                });

            modelBuilder.Entity("ExhibitionExhibit", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", null)
                        .WithMany()
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibEx_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", null)
                        .WithMany()
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibEx_Exhibition");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AnalyticsLog", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("AnalyticsLogs")
                        .HasForeignKey("ExhibitId")
                        .HasConstraintName("FK_Analytics_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("AnalyticsLogs")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_Analytics_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", "Visitor")
                        .WithMany("AnalyticsLogs")
                        .HasForeignKey("VisitorId")
                        .HasConstraintName("FK_Analytics_Visitor");

                    b.Navigation("Exhibit");

                    b.Navigation("Museum");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AuditLog", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Bookmark", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookmarks_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", "Visitor")
                        .WithMany("Bookmarks")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookmarks_Visitor");

                    b.Navigation("Exhibit");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Category", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("Categories")
                        .HasForeignKey("MuseumId")
                        .HasConstraintName("FK_Categories_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Categories_Parent");

                    b.Navigation("Museum");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CatTrans_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ContentVersion", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("ContentVersions")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_ContentVersions_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "PublishedByNavigation")
                        .WithMany("ContentVersions")
                        .HasForeignKey("PublishedBy")
                        .HasConstraintName("FK_ContentVersions_Publisher");

                    b.Navigation("Museum");

                    b.Navigation("PublishedByNavigation");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Category", "Category")
                        .WithMany("Exhibits")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Exhibits_Category");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "CreatedByNavigation")
                        .WithMany("ExhibitCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Exhibits_CreatedBy");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.MuseumMap", "Map")
                        .WithMany("Exhibits")
                        .HasForeignKey("MapId")
                        .HasConstraintName("FK_Exhibits_Map");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("Exhibits")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_Exhibits_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "UpdatedByNavigation")
                        .WithMany("ExhibitUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_Exhibits_UpdatedBy");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Map");

                    b.Navigation("Museum");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitArasset", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("ExhibitArassets")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ARAssets_Exhibit");

                    b.Navigation("Exhibit");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitImage", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("ExhibitImages")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibitImages_Exhibit");

                    b.Navigation("Exhibit");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitMetadatum", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.AgeGroup", "AgeGroup")
                        .WithMany("ExhibitMetadata")
                        .HasForeignKey("AgeGroupId")
                        .HasConstraintName("FK_ExhibMeta_Age");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithOne("ExhibitMetadatum")
                        .HasForeignKey("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitMetadatum", "ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibMeta_Exhib");

                    b.Navigation("AgeGroup");

                    b.Navigation("Exhibit");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitTranslation", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("ExhibitTranslations")
                        .HasForeignKey("ExhibitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibitTrans_Exhibit");

                    b.Navigation("Exhibit");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("Exhibitions")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_Exhibitions_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Theme", "Theme")
                        .WithMany("Exhibitions")
                        .HasForeignKey("ThemeId")
                        .HasConstraintName("FK_Exhibitions_Theme");

                    b.Navigation("Museum");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ExhibitionTranslation", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", "Exhibition")
                        .WithMany("ExhibitionTranslations")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExhibTrans_Exhibition");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.MapPoi", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.MuseumMap", "Map")
                        .WithMany("MapPois")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MapPOIs_Map");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.MuseumMap", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("MuseumMaps")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MuseumMaps_Museum");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.OfflinePackage", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("OfflinePackages")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_OfflinePackages_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.ContentVersion", "Version")
                        .WithMany("OfflinePackages")
                        .HasForeignKey("VersionId")
                        .IsRequired()
                        .HasConstraintName("FK_OfflinePackages_Version");

                    b.Navigation("Museum");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.RefreshToken", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.SystemConfiguration", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.User", "UpdatedByNavigation")
                        .WithMany("SystemConfigurations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_SysConfig_User");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Tag", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tags_TagGroup");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Theme", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("Themes")
                        .HasForeignKey("MuseumId")
                        .HasConstraintName("FK_Themes_Museum");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Ticket", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Type");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Transaction", "Transaction")
                        .WithMany("Tickets")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_Tickets_Transaction");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", "Visitor")
                        .WithMany("Tickets")
                        .HasForeignKey("VisitorId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Visitor");

                    b.Navigation("TicketType");

                    b.Navigation("Transaction");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TicketType", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", "Exhibition")
                        .WithMany("TicketTypes")
                        .HasForeignKey("ExhibitionId")
                        .HasConstraintName("FK_TicketTypes_Exhibition");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("TicketTypes")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_TicketTypes_Museum");

                    b.Navigation("Exhibition");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRoute", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.AgeGroup", "AgeGroup")
                        .WithMany("TourRoutes")
                        .HasForeignKey("AgeGroupId")
                        .HasConstraintName("FK_TourRoutes_AgeGroup");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("TourRoutes")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_TourRoutes_Museum");

                    b.Navigation("AgeGroup");

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRouteExhibit", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("TourRouteExhibits")
                        .HasForeignKey("ExhibitId")
                        .IsRequired()
                        .HasConstraintName("FK_TourRouteExhibits_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.TourRoute", "TourRoute")
                        .WithMany("TourRouteExhibits")
                        .HasForeignKey("TourRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourRouteExhibits_Route");

                    b.Navigation("Exhibit");

                    b.Navigation("TourRoute");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRouteTranslation", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.TourRoute", "TourRoute")
                        .WithMany("TourRouteTranslations")
                        .HasForeignKey("TourRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourRouteTrans_Route");

                    b.Navigation("TourRoute");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Transaction", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Method");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", "Visitor")
                        .WithMany("Transactions")
                        .HasForeignKey("VisitorId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Visitor");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.User", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("Users")
                        .HasForeignKey("MuseumId")
                        .HasConstraintName("FK_Users_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Role");

                    b.Navigation("Museum");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.VisitedExhibit", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", "Exhibit")
                        .WithMany("VisitedExhibits")
                        .HasForeignKey("ExhibitId")
                        .IsRequired()
                        .HasConstraintName("FK_VisitedExhibits_Exhibit");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Museum", "Museum")
                        .WithMany("VisitedExhibits")
                        .HasForeignKey("MuseumId")
                        .IsRequired()
                        .HasConstraintName("FK_VisitedExhibits_Museum");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", "Visitor")
                        .WithMany("VisitedExhibits")
                        .HasForeignKey("VisitorId")
                        .IsRequired()
                        .HasConstraintName("FK_VisitedExhibits_Visitor");

                    b.Navigation("Exhibit");

                    b.Navigation("Museum");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permission");

                    b.HasOne("HistoricalMuseumAudioGuide.Repository.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Role");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.AgeGroup", b =>
                {
                    b.Navigation("ExhibitMetadata");

                    b.Navigation("TourRoutes");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("Exhibits");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.ContentVersion", b =>
                {
                    b.Navigation("OfflinePackages");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibit", b =>
                {
                    b.Navigation("AnalyticsLogs");

                    b.Navigation("Bookmarks");

                    b.Navigation("ExhibitArassets");

                    b.Navigation("ExhibitImages");

                    b.Navigation("ExhibitMetadatum");

                    b.Navigation("ExhibitTranslations");

                    b.Navigation("TourRouteExhibits");

                    b.Navigation("VisitedExhibits");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Exhibition", b =>
                {
                    b.Navigation("ExhibitionTranslations");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Museum", b =>
                {
                    b.Navigation("AnalyticsLogs");

                    b.Navigation("Categories");

                    b.Navigation("ContentVersions");

                    b.Navigation("Exhibitions");

                    b.Navigation("Exhibits");

                    b.Navigation("MuseumMaps");

                    b.Navigation("OfflinePackages");

                    b.Navigation("Themes");

                    b.Navigation("TicketTypes");

                    b.Navigation("TourRoutes");

                    b.Navigation("Users");

                    b.Navigation("VisitedExhibits");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.MuseumMap", b =>
                {
                    b.Navigation("Exhibits");

                    b.Navigation("MapPois");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Theme", b =>
                {
                    b.Navigation("Exhibitions");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.TourRoute", b =>
                {
                    b.Navigation("TourRouteExhibits");

                    b.Navigation("TourRouteTranslations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Transaction", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ContentVersions");

                    b.Navigation("ExhibitCreatedByNavigations");

                    b.Navigation("ExhibitUpdatedByNavigations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SystemConfigurations");
                });

            modelBuilder.Entity("HistoricalMuseumAudioGuide.Repository.Entities.Visitor", b =>
                {
                    b.Navigation("AnalyticsLogs");

                    b.Navigation("Bookmarks");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");

                    b.Navigation("VisitedExhibits");
                });
#pragma warning restore 612, 618
        }
    }
}
